// Source: https://secure.wikimedia.org/wikipedia/en/wiki/Leet#Orthography
var LEET_TABLE = {
    "a" : Array("@", "4"),
    "b" : Array("8", "|3"),
    "c" : Array("<"),
    "d" : Array("|)", "[)"),
    "e" : Array("3"),
    "f" : Array("|="),
    "g" : Array("9"),
    "h" : Array("#", "|-|", "]-["),
    "i" : Array("1", "!", "|"),
    "j" : Array("_/"),
    "k" : Array("|<"),
    "l" : Array("1", "|", "|_"),
    "m" : Array("/\\/\\", "|\\/|", "|v|", "//\\\\//\\\\", "/V\\"),
    "n" : Array("|\\|", "/\\/", "//\\\\//"),
    "o" : Array("0", "()", "[]", "."),
    "p" : Array("|o", "|*", "|>"),
    "q" : Array("9"),
    "r" : Array("2"),
    "s" : Array("5", "$", "z"),
    "t" : Array("7", "+", "1"),
    "u" : Array("|_|", "\\_/"),
    "v" : Array("\\/", "\\\\//"),
    "w" : Array("\\/\\/", "vv", "\\\\//\\\\//"),
    "x" : Array("%", "><"),
    "y" : Array(),
    "z" : Array()
};
